version: '3.8'

services:
  # for flask application
  sentinel-app:
    build:
      context: ./app
    container_name: sentinel-app
    ports:
      - "5000:5000"
    networks:
      - sentinel-network

  # for auto-healing monitor
  sentinel-monitor:
    build:
      context: ./monitor 
    container_name: sentinel-monitor
    environment:
      - APP_URL=http://sentinel-app:5000/health
      - CONTAINER_NAME=sentinel-app
      - CHECK_INTERVAL=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sentinel-network
    depends_on:
      - sentinel-app

networks:
  sentinel-network:
    driver: bridge

